pipeline:
  publish:
    image: plugins/docker
    repo: futurelearn/drone-slack
    tags:
      - latest
      - "${DRONE_BUILD_NUMBER}"
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
