pipeline:
  publish:
    image: plugins/docker
    repo: futurelearn/drone-slack
    tags:
      - latest
      - "${DRONE_BUILD_NUMBER}"
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
  publish branch:
    image: plugins/docker
    repo: futurelearn/drone-mail
    tags:
      - "${DRONE_COMMIT_BRANCH}"
    secrets: [ docker_username, docker_password ]
    when:
      branch:
      exclude: [ master ]
